### ISSUE TITLE
A request to add Wine-Proton

### ISSUE THREAD

**Issue by Ahmed-E-86** [Heroic-Games-Launcher/heroic-wine-downloader#5]
Wine-Proton builds are made by Kron4ek -> https://github.com/Kron4ek/Wine-Builds

They are similar to Wine-GE which can be used outside of Steam.

Links from Kron4ek GitHub-repo:

[wine-6.3-8-proton-amd64.tar.xz](https://github.com/Kron4ek/Wine-Builds/releases/download/6.3-8-proton/wine-6.3-8-proton-amd64.tar.xz)
[wine-5.13-6-proton-amd64.tar.xz](https://github.com/Kron4ek/Wine-Builds/releases/download/5.13-6-proton/wine-5.13-6-proton-amd64.tar.xz)

Older links can be downloaded from MEGA Cloud:

[wine-5.0-9-proton-amd64.tar.xz](https://mega.nz/folder/ZZUV1K7J#kIenmTQoi0if-SAcMSuAHA/file/tUtBXQ7Q)
[wine-4.11-12-proton-amd64.tar.xz](https://mega.nz/folder/ZZUV1K7J#kIenmTQoi0if-SAcMSuAHA/file/9N9xxKJI)
[wine-4.2-8-proton-amd64.tar.xz](https://mega.nz/folder/ZZUV1K7J#kIenmTQoi0if-SAcMSuAHA/file/5QlUVZIT)
[wine-3.16-9-proton-amd64.tar.xz](https://mega.nz/folder/ZZUV1K7J#kIenmTQoi0if-SAcMSuAHA/file/UN9mnBhQ)
[wine-3.7-8-proton-amd64.tar.xz](https://mega.nz/folder/ZZUV1K7J#kIenmTQoi0if-SAcMSuAHA/file/dQlCXZjL)

You can add them to a GitHub repo, or I will do that if you want.

**Comment by Nocccer** [comment]
What i will do is adding this: https://api.github.com/repos/Kron4ek/Wine-Builds/releases

So everything you can downlaod from his github release page, can be then download via this library and later in Heroic
Supporting older version in my eyes is not needed and also would mean alot of changes.

**Comment by Ahmed-E-86** [comment]
There are older games @ protondb.com that only have good reports under Proton 5.0 or Proton 4.11. The idea is the user check the compatibility of the game @ protondb.com then use the same version to run the game.

Sample of games that run fine under older Proton versions:

https://www.protondb.com/app/339340 -> Proton 5.0
https://www.protondb.com/app/368370 -> Proton 4.11

If it is a hard thing to do, I will create a GitHub repo with older versions and I will keep updating it with newer versions if you want.

**Comment by Nocccer** [comment]
We don't will implement a compatibility checker and adding support for older version which are not provided by the release section of a github repository are hard to implement. Also proton is not really working outside of steam. If Wine-proton is meant to work outside of steam aswell, i will add the github repository nothing more.

And if a game runs with proton 5 or 4 it will run pretty fine with proton 6 aswell

**Comment by Ahmed-E-86** [comment]
That is fine. Thanks for your help.

**Comment by Nocccer** [comment]
Ok i can't implement that without alot of changes. He is splitting each part in seperate archives instead in one. 
Thought it is just one archive like Wine-ge which contains everything.
If you familiar with Typescript, maybe implement it, but for now i will drop it. 
Or you could create a bundle archive same structure like wine-ge and upload it in a seperated github repository.

**Comment by Ahmed-E-86** [comment]
I have no prior experience with Typescript, and I do not know how to create a bundle achieve like wine-ge, so there is nothing I can do to help. Thanks anyway.
