### ISSUE TITLE
HGL on flathub can't download wine

### ISSUE THREAD

**Issue by lumingzh** [Heroic-Games-Launcher/heroic-wine-downloader#9]
OS: fedora silverblue 35
GE: gnome shell 41

Installed HGL from flathub, everything seems normal except can't download wine/proton from github.

The terminal messages are:
```
(13:31:45) INFO:    [Frontend]:        Refreshing wine downloader releases
(13:31:45) INFO:    [WineDownloader]:  Updating wine versions info
(13:31:51) INFO:    [WineDownloader]:  wine versions updated
(13:32:35) INFO:    [WineDownloader]:  Start installation of wine version Proton-7.3-GE-1
(node:162) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 progressOfProton-7.3-GE-1 listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `exe --trace-warnings ...` to show where the warning was created)
(13:34:01) INFO:    [DXVKInstaller]:   downloaded dxvk
(13:34:01) INFO:    [DXVKInstaller]:   extracting dxvk
(13:34:01) INFO:    [DXVKInstaller]:   extracting dxvk updated!
(13:34:37) ERROR:   [WineDownloader]:  Download of Proton-7.3-GE-1 failed with:
 Download of https://github.com/GloriousEggroll/proton-ge-custom/releases/download/7.3-GE-1/Proton-7.3-GE-1.tar.gz failed with exit code:
 56!
(13:37:17) INFO:    [WineDownloader]:  Start installation of wine version Proton-GE-Proton7-9
(node:162) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 progressOfProton-GE-Proton7-9 listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(13:39:19) ERROR:   [WineDownloader]:  Download of Proton-GE-Proton7-9 failed with:
 Download of https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton7-9/GE-Proton7-9.tar.gz failed with exit code:
 56!
```
But I can download it by browser normally.

**Comment by Nocccer** [comment]
Tested it on Pop Os and everything worked. I get the warning toobut this is not the issue here.

Can you run `curl -L https://github.com/GloriousEggroll/proton-ge-custom/releases/download/7.3-GE-1/Proton-7.3-GE-1.tar.gz -o <path-where-to-download> -#` from terminal (`<path-where-to-download>` could be `~/Proton-7.3-GE-1.tar.gz` )? 
This is what heroic-wine-downloader calls and i assume that something with your curl installation is not correct or your system blocks something.

**Comment by lumingzh** [comment]
@Nocccer I tested that, maybe the download speed is slow but curl indeed can download it. And HGL always fail.

**Comment by lumingzh** [comment]
@Nocccer I wonder if I can copy the download file to the directory where it should be to make HGL skip the download step. However I don't know the cache path.

**Comment by lumingzh** [comment]
@Nocccer And one more question, the [proton](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton) and [proton-ge](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE) all have been published as runtime on flathub, why not use them?

**Comment by lumingzh** [comment]
OK, I find the proton installing path and copy the extracted files to the directory, HGL recognized it successfully and game run normally. Awesome!
